// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv42NVS-z5p-m-n6xvtcWMAqmqUrCQMs0',
    appId: '1:51124256983:web:fdad8360d732444bc47092',
    messagingSenderId: '51124256983',
    projectId: 'codethon-53527',
    authDomain: 'codethon-53527.firebaseapp.com',
    storageBucket: 'codethon-53527.firebasestorage.app',
    measurementId: 'G-4Z15VCC1NL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF-a3enbIah06bL3ZzrO5LRNw_Lod8guc',
    appId: '1:51124256983:android:a572db9d0099c40ec47092',
    messagingSenderId: '51124256983',
    projectId: 'codethon-53527',
    storageBucket: 'codethon-53527.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ-AMjFuonW0yEoZ67R9pi2uMqURBOSwE',
    appId: '1:51124256983:ios:7f198ac99c2affd5c47092',
    messagingSenderId: '51124256983',
    projectId: 'codethon-53527',
    storageBucket: 'codethon-53527.firebasestorage.app',
    iosBundleId: 'com.example.codethon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ-AMjFuonW0yEoZ67R9pi2uMqURBOSwE',
    appId: '1:51124256983:ios:7f198ac99c2affd5c47092',
    messagingSenderId: '51124256983',
    projectId: 'codethon-53527',
    storageBucket: 'codethon-53527.firebasestorage.app',
    iosBundleId: 'com.example.codethon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv42NVS-z5p-m-n6xvtcWMAqmqUrCQMs0',
    appId: '1:51124256983:web:eb90c70c46aed344c47092',
    messagingSenderId: '51124256983',
    projectId: 'codethon-53527',
    authDomain: 'codethon-53527.firebaseapp.com',
    storageBucket: 'codethon-53527.firebasestorage.app',
    measurementId: 'G-P65LJ2XYLJ',
  );
}
