name: codethon
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications:
    git:
      url: https://github.com/MaikuB/flutter_local_notifications.git 
      path: flutter_local_notifications
  http: ^1.2.1
  intl: ^0.19.0
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.12.2
  cupertino_icons: ^1.0.8
  logger: ^2.0.2
  flutter_map_marker_cluster: ^1.1.1
  lottie: ^2.6.0
  geolocator: ^11.0.0
  geocoding: ^2.2.0
  universal_html: ^2.2.2
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  webview_flutter: ^4.4.2
  flutter_launcher_icons: ^0.13.1
  dropdown_button2: ^2.3.9
  table_calendar: ^3.0.9
  shared_preferences: ^2.2.2
  dropdown_search: ^5.0.6
  google_sign_in: ^6.3.0
  crypto: ^3.0.3
  flutter_webrtc: 0.9.46
  firebase_messaging: ^14.7.4
  googleapis_auth: ^1.4.0
  url_launcher: ^6.2.5
  onesignal_flutter: ^5.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/firebase_service_account.json
    - assets/lottie/rain.json
    - assets/lottie/wind.json
    - assets/lottie/radar.json
    - assets/lottie/load.json
    - assets/lottie/load2.json
    - assets/lottie/asistente.json
    - assets/lottie/load3.json
    - assets/lottie/weather/cloudy.json
    - assets/lottie/weather/fog.json
    - assets/lottie/weather/lighting.json
    - assets/lottie/weather/night.json
    - assets/lottie/weather/night-cloud.json
    - assets/lottie/weather/night-rain.json
    - assets/lottie/weather/rain-light.json
    - assets/lottie/weather/sunny.json
    - assets/lottie/intro.json
    - assets/lottie/alerta.json
    - assets/lottie/apagon.json
    - assets/lottie/incendio.json
    - assets/lottie/inundacion.json
    - assets/lottie/load-votaciones.json
    - assets/lottie/night-time.json
    - assets/lottie/day-time.json
    - assets/lottie/terremoto.json
    - assets/lottie/tornado.json
    - assets/images/maps_card.jpg
    - assets/images/maps_card_night.jpg
    - assets/images/google.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

dependency_overrides:
  web: ^0.5.1


