name: codethon
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  intl: ^0.19.0
  firebase_core: ^2.25.4
  cloud_firestore: ^4.12.2
  cupertino_icons: ^1.0.8
  logger: ^2.0.2
  flutter_map_marker_cluster: ^1.1.1 
  lottie: ^2.6.0
  geolocator: ^11.0.0
  geocoding: ^2.2.0
  universal_html: ^2.2.2
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  webview_flutter: ^4.4.2
  flutter_launcher_icons: ^0.13.1
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/rain.json
    - assets/lottie/wind.json
    - assets/lottie/radar.json
    - assets/lottie/load.json
    - assets/lottie/load2.json
    - assets/lottie/load3.json
    - assets/lottie/weather/cloudy.json
    - assets/lottie/weather/fog.json
    - assets/lottie/weather/lighting.json
    - assets/lottie/weather/night.json
    - assets/lottie/weather/night-cloud.json
    - assets/lottie/weather/night-rain.json
    - assets/lottie/weather/rain-light.json
    - assets/lottie/weather/sunny.json
    - assets/lottie/intro.json
    - assets/images/maps_card_bg.png
    - assets/images/maps_card.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

