name: codethon
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core (obligatorio para cualquier servicio de Firebase)
  firebase_core: ^2.25.4

  # Cloud Firestore (base de datos)
  cloud_firestore: ^4.12.2

  # Íconos estilo iOS
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
